stages:
- test

test_job:2.7:
  image: python:2.7
  stage: test
  services:
  - elasticsearch:2
  script:
  - apt-get update && apt-get install -y make libgdal1h python-virtualenv
  - make test python="python2.7"

test_job:3.5:
  image: python:3.5
  stage: test
  services:
  - elasticsearch:2
  script:
  - apt-get update && apt-get install -y make libgdal1h
  - make test python="python3.5"
