version: '3'
networks:
  default:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:2
    networks:
      - default
    ports:
      - "127.0.0.1:9200:9200"

  test:
    build:
      context: .
    networks:
      - default
    volumes:
      - .:/django-inelastic-models
