version: '3'

secrets:
  ESPassword:
    file: ./es_password.txt

networks:
  default:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:8.4.1
    networks:
      - default
    ports:
      - "9200:9200"
    environment:
      - cluster.name=inelastic_models
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD_FILE=/run/secrets/ESPassword
      - ELASTIC_CLIENT_APIVERSIONING=1
    mem_limit: 512M
    mem_swappiness: 1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    secrets:
      - ESPassword

  test:
    build:
      context: docker
    networks:
      - default
    volumes:
      - .:/django-inelastic-models
