version: '3'

networks:
  default:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:7.12.0
    networks:
      - default
    ports:
      - "9200:9200"
    environment:
      - cluster.name=inelastic_models
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    mem_limit: 2g
    mem_swappiness: 0
    ulimits:
      memlock:
        soft: -1
        hard: -1

  test:
    build:
      context: docker
    networks:
      - default
    volumes:
      - .:/django-inelastic-models
