

secrets:
  ESPassword:
    file: ./es_password.txt

networks:
  default:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:8.18.0
    networks:
      - default
    ports:
      - "9201:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=inelastic_models
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=elasticsearch
      - ELASTIC_PASSWORD_FILE=/run/secrets/ESPassword
      - ELASTIC_CLIENT_APIVERSIONING=1
    mem_swappiness: 1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    secrets:
      - ESPassword

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - default
    volumes:
      - .:/django-inelastic-models
