[project]

name = "django-inelastic-models"
version = "9.0.0"
description = "Declarative Elasticsearch indexes for Django models."
readme = "README.rst"
authors = [
  {name = "Thom Linton", email="tlinton@pdx.edu"}
]
maintainers = [
  {name = "Thom Linton", email = "tlinton@pdx.edu"}
]

requires-python = ">=3.11"
classifiers = [
  "Development Status :: 5 - Production/Stable",

  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",

  # Pick your license as you wish
  # "License :: ",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "python-dateutil >=2.8.0, <3.0",
  "elasticsearch ~= 9.4.0",
  "django >=4.2, <6.0"
]

# List additional groups of dependencies here (e.g. development
# dependencies). Users will be able to install these using the "extras"
# syntax, for example:
#
#   $ pip install sampleproject[dev]
#
# Similar to `dependencies` above, these must be valid existing
# projects.
[project.optional-dependencies]

# List URLs that are relevant to your project
#
# This field corresponds to the "Project-URL" and "Home-Page" metadata fields:
# https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
# https://packaging.python.org/specifications/core-metadata/#home-page-optional
#
# Examples listed include a pattern for specifying where the package tracks
# issues, where the source is hosted, where to say thanks to the package
# maintainers, and where to support the project financially. The key is
# what's used to render the link text on PyPI.
[project.urls]
"Homepage" = "https://psu-oit-arc.github.io/django-inelastic-models"
"Bug Reports" = "https://github.com/PSU-OIT-ARC/django-inelastic-models/issues"
"Source" = "https://github.com/PSU-OIT-ARC/django-inelastic-models"

# The following would provide a command line executable called `sample`
# which executes the function `main` from this package when invoked.
[project.scripts]

# This is configuration specific to the `setuptools` build backend.
# If you are using a different build backend, you will need to change this.
[tool.setuptools]

[tool.setuptools.packages.find]
where = ["src"]
include = ["inelastic_models*"]
namespaces = true

[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"
