FROM python:3.7-buster
MAINTAINER Thom Linton <tlinton@pdx.edu>


RUN apt-get update && \
    apt-get install -y \
        make build-essential \
        python3-venv

WORKDIR /django-inelastic-models
